spring:
  application:
    name: accounts-service
  datasource:
    url: jdbc:mysql://${mysqldocker.accounts.container.name:localhost}:3306/ecommerce_accounts_db?&useSSL=false&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME:davidking}
    password: ${SPRING_DATASOURCE_PASSWORD:davidking!!}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
      preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
  health:
    ratelimiters:
      enabled: true
    circuitbreakers:
      enabled: true

# docker custom variables
mysqldocker:
  accounts:
    container:
      name: accounts_mysql_container
  orders:
    container:
      name: orders_mysql_container
  products:
    container:
      name: products_mysql_container
  shipments:
    container:
      name: shipments_mysql_container